project/urls.py
from django.contrib import admin
from django.urls import path, include
from todo import urls


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('todo.urls')),
    ]

todo/urls.py
from django.urls import path, include
from . import views

app_name = 'todo'

urlpatterns = [
        path('', views.index, name='index'),
        path('todo_list_partial', views.todo_list_partial, name='todo_list_partial'),
        path('todo_list_partial/<int:pk>', views.todo_details_partial, name='todo_details_partial'),
        path('create/', views.create, name='create'),
        path('rerank/', views.rerank, name='rerank',)
        ]

todo/models.py
from django.db import models, transaction


class Todo(models.Model):
    title   = models.CharField(max_length=200, db_index=True)
    text    = models.TextField()
    rank    = models.IntegerField(db_index=True)

    class Meta:
        ordering = ['rank']

    def __str__(self):
        return f'{self.title} - {self.text} - ({self.rank}) - {self.pk}'

    @classmethod
    def create(cls, title=title, text=text):
        cls.objects.create(
                title=title,
                text=text,
                rank=cls.highest_rank + 1)

    @classmethod
    @property
    def highest_rank(cls):
        return int(cls.objects.all().aggregate(models.Max('rank'))['rank__max'] or 0)


    def rerank(self, new_rank):
        with transaction.atomic():
            if self.rank == new_rank:
                return
            elif new_rank < self.rank:
                delta = 1
                todos = type(self).objects.filter(rank__gte=new_rank).filter(rank__lte=self.rank)
            else:
                delta = -1
                todos = type(self).objects.filter(rank__gte=self.rank).filter(rank__lte=new_rank)
            for todo in todos:
                if todo.rank == self.rank:
                    todo.rank = new_rank
                else:
                    todo.rank += delta

            type(self).objects.bulk_update(todos, fields=('rank',))

    @classmethod
    def rerank_by_list(cls, reranked):
        todos = [todo.pk for todo in cls.objects.all()]
        for i, samples in enumerate(zip(todos, reranked)):
            if not samples[0] == samples[1]:
                new_i_index = reranked.index(todos[i])
                if new_i_index > i + 1:
                    #down
                    cls.objects.get(pk=todos[i]).rerank(new_i_index+1)
                else:
                    #up or swap
                    cls.objects.get(pk=reranked[i]).rerank(new_i_index)
                break

    def delete(self, *arg, **kwargs):
        self.rerank(type(self).highest_rank)
        super(type(self), self).delete(*arg, **kwargs)

todo/views.py
from django.shortcuts import render, get_object_or_404
from .models import Todo
from django.http import HttpResponse


def index(request):
    return render(request, 'todo/index.html', {})

def todo_list_partial(request):
    todos = Todo.objects.all()

    return render(request, 'todo/todo_list_partial.html', {'todos': todos})

def create(request):
    Todo.create(title=request.POST['title'], text=request.POST['text'])
    response = render(request, 'todo/index.html', {})
    response['HX-Redirect'] = request.META['HTTP_HX_CURRENT_URL']
    return response

def todo_details_partial(request, pk):
    todo = get_object_or_404(Todo, pk=pk)

    if request.method == 'GET':
        #RETURN FORM
        return render(request, 'todo/todo_details_partial.html', {'todo': todo})

    if request.method == 'DELETE':
        #DELETE ELEMT FROM DB
        todo.delete()

    if request.method == 'PUT':
        todo.title =  request.PUT[f'todo_{todo.pk}_title']
        todo.text = request.PUT[f'todo_{todo.pk}_text']
        todo.save()

    todos = Todo.objects.all()
    return render(request, 'todo/todo_list_partial.html', {'todos': todos})

def rerank(request):
    reranked = [int(todo) for todo in request.POST.getlist('todo_order')]
    Todo.rerank_by_list(reranked)
    return HttpResponse(status=204)

todo/templates/todo/index.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
         <link rel="stylesheet" href="https://cdn.rawgit.com/kimeiga/bahunya/css/bahunya-0.1.3.css"/>
<style type="text/css">
.col-element {
width: 50%;
}
.left {
float: left;
}
.right {
float: right;
}
.clearfix {
clear: both;
}
.clickable {
cursor: pointer;
}
</style>
<title>
Todo
</title>
    </head>

    <body>
        <header>
            <nav>
                <h1>
                    <a href="{% url 'todo:index' %}">Todo</a>
                </h1>
                <input type="checkbox" id="menu-toggle">
                <label for="menu-toggle"> &#9776; </label>
                <a href="#">STARTUP</a>
                <a href="#">MINIMAL</a>
                <a href="#">BOLD</a>
            </nav>
            <h1>Todo</h1>
        </header>

        <main>
            <section class="left col-element">
                <h3>Todo List</h3>
                <div id="todo_list"
                    hx-swap="outerHTML"
                    hx-get="{% url 'todo:todo_list_partial' %}"
                    hx-trigger="load">
                </div>
            </section>
            <section class="right col-element"><h3>Add todo</h3>

            <form>
                <fieldset>
                    <input type="text" name="title" size="30" placeholder="Title">
                    <textarea name="text" width="30" height="5" placeholder="Text"></textarea>
                    <button
                        hx-post="{% url 'todo:create'  %}"
                        hx-trigger="click"
                        hx-swap="none"
                        target="html">Submit</button>
                </fieldset>

            </form>
            </section>
            <div class="clearfix"></div>
        </main>

        <footer>
            That's all, folks!
        </footer>

        <script src="https://unpkg.com/htmx.org@1.8.6" integrity="sha384-Bj8qm/6B+71E6FQSySofJOUjA/gq330vEqjFx9LakWybUySyI1IQHwPtbTU7bNwx" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/sortablejs@latest/Sortable.min.js"></script>
        <script>
            document.body.addEventListener('htmx:configRequest', (event)=> {event.detail.headers['X-CSRFToken'] = '{{ csrf_token }}'; })

            htmx.onLoad(function(content) {
    var sortables = content.querySelectorAll(".sortable");
    for (var i = 0; i < sortables.length; i++) {
      var sortable = sortables[i];
      new Sortable(sortable, {
          animation: 150,
          ghostClass: 'blue-background-class'
      });
    }
})

        </script>



    </body>

todo/templates/todo/todo_details_partial.html
<div id="todo_{{todo.pk}}">

    <form>
        <fieldset>
        <div>
            {{todo.rank}} - <input type="text" name="todo_{{todo.pk}}_title" value="{{todo.title}}" />
        </div>
        <div>
            <textarea name="todo_{{todo.pk}}_text" rows="5" cols="30"> {{todo.text}} </textarea>
        </div>
        <button
            hx-put="{% url 'todo:todo_details_partial' todo.pk %}"
            hx-target="#todo_list"
            hx-swap="outerHTML"> Update </button>

        <button
            hx-delete="{% url 'todo:todo_details_partial' todo.pk %}"
            hx-target="#todo_list"
            hx-swap="outerHTML"> Delete </button>

        </fieldset>
    </form>


</div>

todo/templates/todo/todo_list_partial.html
<div id="todo_list">
    <form class="sortable" hx-post="{% url 'todo:rerank' %}" hx-trigger="end">

    {% for todo in todos %}

    <div id="todo_{{ todo.pk }}" class="clickable"
        hx-get="{% url 'todo:todo_details_partial' todo.pk %}"
        hx-trigger="click"
        hx-target="this"
        hx-swap="outerHTML"
        >
        <div>{{ todo.rank }} - {{ todo.title }} ({{ todo.pk }})  </div>

        <input type="hidden" name="todo_order" value="{{todo.pk }}"/>
    </div>


    {% endfor %}
    </form>
</div>